"""The Uninstall tab's frontend fixture — generated by the REAL build code from a synthetic GA4.

    python -m tests.make_uninstall_fixture        # rewrites tests/fixtures/uninstall_sample.json

Seven daily build runs (19–25 Sep 2026, 12:00 UTC → GA4 data till 17–23 Sep) against a fake GA4 (Admin +
Data API, tests.uninstall_synth) go through admob_iq.uninstall_build.run_uninstall exactly as the hourly
build does: discovery, full then incremental fetches, evaluation, alert episodes, send_alerts (dry run) and
mark_notified. Every app, name, package and id is made up; nothing here is real data.

The fake GA4 answers like Firebase does: a day's app_remove arrives LATE (80% of it when the day is 2 days
old, 99% at 7 — LATE_SHARE), so the newest 7 days are provisional (hatched in the tab), the incremental
re-reads measure that lateness ("lateness" in the asset), and no good news is read into a day still filling.

The apps cover what the tab has to show:
  * Demo Caller – Test App  big + stable, a new version (zoom), D1 uninstall rising  → watch (sent 21 Sep, "kaccha")
                            installs of 7–19 Mar left more 2 months later           → D180 moved: old installs, so
                                                                                       info only ("Purane badlaav"),
                                                                                       never an alert
                                                                                       — ONE alert while it
                                                                                       lasts, though its newest
                                                                                       installs still read low;
                                                                                       GA4 keeps its install-day
                                                                                       USERS 150 days only: the
                                                                                       older days come from the
                                                                                       events ("(events) se andaza")
  * Demo Flashlight         growing, D0 uninstall falling since 25 Aug (settled)    → good; the summary verdict:
                                                                                       more kept 7 days after
                                                                                       install than the month before
  * Demo Notes              20 days old (28-day actives still filling: no rate yet)  → "naya", every day
  * Demo QR Scanner         ~35 installs/day                                         → "kam data" rows
  * Demo Weather            uninstall rate stepping up since 12 Sep                  → slow drift warning
  * Demo Launcher           one day with far more uninstalls                         → spike warning (new today,
                                                                                       "kaccha": can only grow);
                                                                                       and 3 Sep's install-day
                                                                                       cells GA4 never returns in
                                                                                       full → "data adhoora", no
                                                                                       alert from it
  * Demo Wallpapers         a day with no app_remove at all (14 Sep)                 → tracking watch once that
                                                                                       day is settled, NO false
                                                                                       "good news", and the
                                                                                       D-rows it touches say so;
                            ~10 months of a few TEST installs before its launch      → launch 16 Jun 2026 found:
                            (from 20 Aug 2025)                                         the test installs hidden
                                                                                       by default ("dikhao"), kept
  * no GA4: no package / no stream / a stream that errors / an app added today whose fetch was deferred /
    a second AdMob app for the Caller's Play package (fetched and alerted once, under the Caller)
"""

import contextlib
import gzip
import io
import json
import os
import sys
import tempfile
from datetime import date, datetime, timedelta, timezone
from unittest import mock

from admob_iq import build_static
from admob_iq.config import settings
from admob_iq.fetch import ga4
from admob_iq.uninstall_build import run_uninstall
from tests.uninstall_synth import AdminFake, Truth, UniStub, wave

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures", "uninstall_sample.json")
E_FINAL = date(2026, 9, 23)
RUN_DAYS = [datetime(2026, 9, d, 12, 0, tzinfo=timezone.utc) for d in range(19, 26)]
OWNER1, OWNER2 = "owner-1@demo.invalid", "owner-2@demo.invalid"
RT1, RT2, TOK1, TOK2 = "rt-demo-1", "rt-demo-2", "tok-demo-1", "tok-demo-2"
P1, P2, P3 = "100000001", "100000002", "100000003"
BIG_LAGS = {0: 300, 1: 40, 2: 25, 3: 15, 4: 10, **{n: 5 for n in range(5, 15)}, **{n: 2 for n in range(15, 31)},
            **{n: 1 for n in range(33, 121, 3)}}
LATE_SHARE = {2: 0.80, 3: 0.88, 4: 0.93, 5: 0.96, 6: 0.98, 7: 0.99}     # of a day's app_remove GA4 shows at that age


def _aid(n):
    return "ca-app-pub-0000000000000000~90000000%02d" % n


# app_id, name, package, (property, stream) or None
APPS = [
    (_aid(1), "Demo Caller – Test App", "com.demo.caller", (P1, "200000001")),
    (_aid(2), "Demo Flashlight", "com.demo.flashlight", (P1, "200000002")),
    (_aid(3), "Demo Notes", "com.demo.notes", (P2, "200000003")),
    (_aid(4), "Demo QR Scanner", "com.demo.qrscanner", (P2, "200000004")),
    (_aid(5), "Demo Weather", "com.demo.weather", (P3, "200000005")),
    (_aid(6), "Demo Launcher", "com.demo.launcher", (P3, "200000006")),
    (_aid(7), "Demo Wallpapers", "com.demo.wallpapers", (P1, "200000007")),
    (_aid(8), "Demo Broken Stream", "com.demo.broken", (P2, "200000008")),
    (_aid(9), "Demo Just Added", "com.demo.justadded", (P3, "200000009")),
    (_aid(10), "Demo No Package", None, None),
    (_aid(11), "Demo No Stream", "com.demo.nostream", None),
    (_aid(12), "Demo Hidden (not selected)", "com.demo.hidden", (P1, "200000012")),
    (_aid(13), "Demo Caller Copy", "com.demo.caller", None),
]
JUST_ADDED, BROKEN, HIDDEN = _aid(9), _aid(8), _aid(12)


def truths():
    E = E_FINAL
    d = lambda n: E - timedelta(days=n)                                  # noqa: E731

    def big_versions(day, a1):
        s = 0.0 if day < date(2026, 9, 10) else min(0.9, 0.1 * ((day - date(2026, 9, 10)).days + 1))
        return {"3.1": int(a1 * (1 - s)), "3.2": int(a1 * s)} if s else {"3.1": a1}

    t = {
        "200000001": Truth(d(239), E, lambda c: int(5000 * wave(c)), lags=BIG_LAGS, old_per_day=400, noise=0.03,
                           bump=lambda c: ({1: 60} if c >= date(2026, 9, 11)
                                           else {60: 70} if d(199) <= c <= d(187) else None),
                           upd=lambda c: 12000 if c == date(2026, 9, 10) else 800, versions=big_versions, seed=1),
        "200000002": Truth(d(74), E, lambda c: int(400 * wave(c)), noise=0.05, old_per_day=20, seed=2,
                           bump=lambda c: {0: -100, 1: 20} if c >= date(2026, 8, 25) else None),
        "200000003": Truth(d(19), E, 150, noise=0.08, seed=3),
        "200000004": Truth(d(199), E, lambda c: int(35 * wave(c, 0.3)), noise=0.2, seed=4),
        "200000005": Truth(d(149), E, lambda c: int(1500 * wave(c)), noise=0.03, seed=5,
                           old_per_day=lambda c: 600 if c >= date(2026, 9, 12) else 150),
        "200000006": Truth(d(119), E, lambda c: int(800 * wave(c)), noise=0.04, seed=6,
                           old_per_day=lambda c: 960 if c == E else 60),
        "200000007": Truth(d(99), E, lambda c: int(300 * wave(c)), noise=0.05, old_per_day=10, seed=7),
        "200000008": Truth(d(99), E, 100, seed=8),
        "200000009": Truth(d(29), E, 100, seed=9),
        "200000012": Truth(d(29), E, 100, seed=12),
    }
    gap = date(2026, 9, 14)                                              # a tracking break: no app_remove that day
    z = t["200000007"]
    z.cells = {k: v for k, v in z.cells.items() if k[1] != gap}
    z.old[gap] = 0
    t0 = E - timedelta(days=399)                                         # test installs long before the launch:
    for i in range((z.start - t0).days):                                 # 0–2 a day on a few testers' phones
        c = t0 + timedelta(days=i)
        k = (c.toordinal() * 37) % 11
        z.new[c] = 2 if k == 0 else 1 if k < 4 else 0
        z.old[c], z.upd[c], z.a1[c], z.a28[c] = 0, 0, z.new[c] + 3, 6
        z.vers[c] = {"1.0": z.a1[c]}
        if z.new[c] and i % 3 == 0:
            z.cells[(c, c + timedelta(days=2))] = 1                      # a tester removed it 2 days later
    z.start = t0
    t["200000006"].short_day = {date(2026, 9, 3): 0.6}                  # cells short at ANY range: incomplete
    caller = t["200000001"]                                              # install-day USERS kept 150 days only
    caller.users_day = lambda day: 1.0 if (caller.asof - day).days <= 150 else 0.04
    for x in t.values():                                                 # Firebase-like late app_remove
        x.late = lambda age: 1.0 if age > 7 else LATE_SHARE.get(age, 0.8)
    return t


def build_fixture(work_dir):
    """Run the seven builds in `work_dir` → {"dashboard_uninstall", "asset", "cohort_files", "sent", "public_log"}."""
    data_dir, out_dir = os.path.join(work_dir, "data"), os.path.join(work_dir, "site")
    os.makedirs(data_dir, exist_ok=True)
    with open(os.path.join(data_dir, "app_store_ids.json"), "w", encoding="utf-8") as f:
        json.dump({"by_id": {aid: pkg for aid, _, pkg, _ in APPS if pkg}}, f)
    tr = truths()
    streams = {p: [("1", "com.stranger.app")] for p in (P1, P2, P3)}   # + a stream that is none of our apps
    for _, _, pkg, route in APPS:
        if route:
            streams[route[0]].append((route[1], pkg))
    admin = AdminFake({TOK1: [P1, P2], TOK2: [P2, P3]}, streams)
    flags = {"broken_tried": False}

    def app(tok, pid, sid):
        if sid == "200000008":
            flags["broken_tried"] = True

            def fail(body):
                raise RuntimeError("HTTP 500: INTERNAL: backend error")
            return UniStub(tr[sid], tok, pid, sid, fail=fail)
        return UniStub(tr[sid], tok, pid, sid)

    s = dict(settings(), ga4_enabled=True, ga4_client_id="demo-cid", ga4_client_secret="demo-sec",
             ga4_refresh_tokens=json.dumps({OWNER1: RT1, OWNER2: RT2}), ga4_refresh_token="",
             ga4_min_hours=20.0, ga4_retry_hours=3.0, ga4_refetch_days=14, ga4_late_days=7, ga4_rebuild_days=28,
             ga4_max_history_days=1300, ga4_run_budget_sec=900, ga4_streams_ttl_hours=168.0, notify_dry_run=True)
    sent = []
    with contextlib.ExitStack() as st:
        st.enter_context(mock.patch.object(ga4.requests, "get", admin.get))
        st.enter_context(mock.patch.object(ga4.requests, "post", admin.post))
        st.enter_context(mock.patch.object(ga4, "_sleep", lambda s: None))
        st.enter_context(mock.patch.object(ga4, "access_token", lambda c, sec, rt: {RT1: TOK1, RT2: TOK2}[rt]))
        st.enter_context(mock.patch.object(ga4, "Ga4App", app))
        log = st.enter_context(contextlib.redirect_stderr(io.StringIO()))
        for i, now in enumerate(RUN_DAYS):
            final = i == len(RUN_DAYS) - 1
            for x in tr.values():                                          # what GA4 has received by this run
                x.asof = (now + timedelta(hours=5, minutes=30)).date()    # (the properties are on IST)
            catalog = [{"app_id": aid, "app_name": name, "account_id": "pub-demo",
                        "selected": aid != HIDDEN and (final or aid != JUST_ADDED)} for aid, name, _, _ in APPS]
            dashboard = {"apps_catalog": catalog, "kpis": {"revenue": 1.0}}
            flags["broken_tried"] = False
            clock = (lambda: 1e6 if flags["broken_tried"] else 0.0) if final else (lambda: 0.0)
            run_uninstall(dashboard, data_dir, out_dir, s, now=now, clock=clock)
            res = build_static.send_alerts(dashboard, s)                  # dry run: formats, never sends
            sent.append({"run": now.strftime("%Y-%m-%dT%H:%MZ"),
                         "telegram": next((r["text"] for r in res if r["channel"] == "telegram"), None),
                         "email": next((r["body"] for r in res if r["channel"] == "email"), None)})
            if not final:                                                  # the final run's alerts stay "new"
                build_static._uninstall_mark_sent(dashboard, data_dir, s, res)
        public_log = log.getvalue().splitlines()
    with gzip.open(os.path.join(out_dir, "uninstall.json.gz"), "rt", encoding="utf-8") as f:
        asset = json.load(f)
    cohort_files = {}
    for name in sorted(os.listdir(out_dir)):
        if name.startswith("uninstall_c_"):
            with gzip.open(os.path.join(out_dir, name), "rt", encoding="utf-8") as f:
                cohort_files[name] = json.load(f)
    return {"dashboard_uninstall": dashboard["uninstall"], "asset": asset, "cohort_files": cohort_files,
            "sent": sent, "public_log": public_log}


def fixture_json(fx):
    body = {"_about": "Synthetic Uninstall-tab data written by the real build code (python -m "
                      "tests.make_uninstall_fixture). dashboard_uninstall = dashboard.json's \"uninstall\" key; "
                      "asset = site/uninstall.json.gz; cohort_files = site/uninstall_c_<key>.json.gz; sent = what "
                      "each of the 7 daily runs would notify (dry run); public_log = the build-log lines. Made-up "
                      "apps only.",
            "dashboard_uninstall": fx["dashboard_uninstall"], "asset": fx["asset"],
            "cohort_files": fx["cohort_files"], "sent": fx["sent"], "public_log": fx["public_log"]}
    return json.dumps(body, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"


def main():
    with tempfile.TemporaryDirectory() as tmp:
        text = fixture_json(build_fixture(tmp))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s (%d KB)" % (os.path.relpath(OUT), len(text.encode("utf-8")) // 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
