"""The Uninstall tab's frontend fixture — generated by the REAL build code from a synthetic GA4.

    python -m tests.make_uninstall_fixture        # rewrites tests/fixtures/uninstall_sample.json

Seven daily build runs (19–25 Sep 2026, 12:00 UTC → GA4 data till 17–23 Sep) against a fake GA4 (Admin +
Data API, tests.uninstall_synth) go through admob_iq.uninstall_build.run_uninstall exactly as the hourly
build does: discovery, full then incremental fetches, evaluation, alert episodes, send_alerts (dry run) and
mark_notified. Every app, name, package and id is made up; nothing here is real data.

The fake GA4 answers like Firebase does: a day's app_remove arrives LATE (80% of it when the day is 2 days
old, 99% at 7 — LATE_SHARE), so the newest 7 days are provisional (hatched in the tab), the incremental
re-reads measure that lateness ("lateness" in the asset), and no good news is read into a day still filling.

The apps cover what the tab has to show:
  * Demo Caller – Test App  big + stable, a new version (zoom), D1 uninstall rising  → watch (sent 21 Sep, "kaccha")
                            installs of 7–19 Mar left more 2 months later           → D180 moved: old installs, so
                                                                                       info only ("Purane badlaav"),
                                                                                       never an alert
                                                                                       — ONE alert while it
                                                                                       lasts, though its newest
                                                                                       installs still read low;
                                                                                       GA4 keeps its install-day
                                                                                       USERS 150 days only: the
                                                                                       older days come from the
                                                                                       events ("(events) se andaza")
  * Demo Flashlight         growing, D0 uninstall falling since 25 Aug (settled)    → good; the summary verdict:
                                                                                       more kept 7 days after
                                                                                       install than the month before
  * Demo Notes              20 days old (28-day actives still filling: no rate yet)  → "naya", every day
  * Demo QR Scanner         ~35 installs/day                                         → "kam data" rows
  * Demo Weather            uninstall rate stepping up since 12 Sep                  → slow drift warning
                            version 4.1 out from 15 Jul (mid-table)                  → a 📦 line in the install-
                                                                                       week table (no zoom: old)
  * Demo Launcher           one day with far more uninstalls                         → spike warning (new today,
                                                                                       "kaccha": can only grow);
                                                                                       and 3 Sep's install-day
                                                                                       cells GA4 never returns in
                                                                                       full (60%) → "Data
                                                                                       incomplete", no alert from
                                                                                       it; the rows it would empty
                                                                                       take older installs
                            20 Aug's install-day cells only ever 94% there          → filled up to the day's
                                                                                       exact total: "≈ Estimate",
                                                                                       used everywhere
                            app_update users jump on 5 Aug (no new version)          → an "update" 📦 line
  * Demo Wallpapers         a day with no app_remove at all (14 Sep)                 → tracking watch once that
                                                                                       day is settled, NO false
                                                                                       "good news", and the
                                                                                       D-rows it touches say so;
                            ~10 months of a few TEST installs before its launch      → launch 16 Jun 2026 found:
                            (from 20 Aug 2025)                                         the test installs hidden
                                                                                       by default ("dikhao"), kept
  * no GA4: no package / no stream / a stream that errors / an app added today whose fetch was deferred /
    a second AdMob app for the Caller's Play package (fetched and alerted once, under the Caller)

UPDATE IMPACT (the "📦 Update impact" card; AdMob revenue on Pacific days is passed in like build_static does — the
properties are on IST, so every GA4 day takes its share of two AdMob days):
  * Demo Caller 3.2 (10 Sep, 10%/day rollout)  old users on 3.2 open the app 15% less and spend 22% less time → returning
                                               DAU below expected + time per user down → ⏳ too early (2 settled days),
                                               then worse for one day ("pakka hone ke liye kal ka data bhi"), then 🛑 HALT
                                               on 21 Sep — alert SENT (Telegram)
  * Demo Flashlight 1.2 (1 Sep)                new users come back more (D1 30% → 36%) → ✅ WIN (a good alert, seeded:
                                               the app's first impact evaluation)
    Demo Flashlight 1.3 (19 Sep)               → ⏳ Too early
  * Demo Wallpapers 2.0 (1 Sep, LOW adoption:  users on 2.0 see a third fewer ads → ad revenue per user −8% with ads per
    a staged rollout stuck at 25%)             user −8% (not the market) → ⚠️ HOLD, "diluted" + slow rollout
  * Demo Weather 4.1 (15 Jul)                  old: no alert; GA4 keeps its user data 60 days here, so new users back
                                               D1 / D7 say "GA4 ab itna purana user data nahi rakhta" (ret_from)
  * Demo Launcher update surge (5 Aug)         kind "update": no version table (rows "No data", the reason)

THE 7 / 14 / 30 / 60-DAY WINDOWS (spec SPEC_WINDOWS; every block carries by_window):
  * Demo Late Drop (440 days)  v1.9 (E−100, clean: its 60-day window final), v2.0 (E−42, instant adoption) and v2.1
                               (E−32, inside v2.0's 30 days: "Mixed"); ads per user −15% from E−24 — after both 7-day
                               after-windows, so both 7-day verdicts stay CONTINUE and nothing is told. v2.0's 30-day
                               window is judged on data day E−2 (run 5: held once) → ⏰ late HOLD SENT in run 6 ("ke 30
                               din baad … pehle 7 din me ye nahi dikha tha … D30 abhi baaki"); its 60 days running
  * Demo Late Told (240 days)  one update (E−50): new users back next day −2.5 points from its a0, lasting → 7-day HOLD
                               (older than 35 days: never alerted), 30-day HOLD with the row told ("7 din ke faisle me
                               pehle hi dikha"), no late alert
  (the Caller's 3.2 and the Flashlight's 1.3 read "running" at 30 / 60; the first run seeds, nothing of it is sent)
"""

import contextlib
import gzip
import io
import json
import os
import sys
import tempfile
from datetime import date, datetime, timedelta, timezone
from unittest import mock

from admob_iq import build_static
from admob_iq.config import settings
from admob_iq.fetch import ga4
from admob_iq.uninstall_build import run_uninstall
from tests.uninstall_synth import (DEFAULT_RET, AdminFake, Truth, UniStub, make_active_store, rollout as shares,
                                   truncate_store, wave)

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures", "uninstall_sample.json")
OUT_ACTIVE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures", "active_sample.json")
E_FINAL = date(2026, 9, 23)
RUN_DAYS = [datetime(2026, 9, d, 12, 0, tzinfo=timezone.utc) for d in range(19, 26)]
OWNER1, OWNER2 = "owner-1@demo.invalid", "owner-2@demo.invalid"
RT1, RT2, TOK1, TOK2 = "rt-demo-1", "rt-demo-2", "tok-demo-1", "tok-demo-2"
P1, P2, P3 = "100000001", "100000002", "100000003"
BIG_LAGS = {0: 300, 1: 40, 2: 25, 3: 15, 4: 10, **{n: 5 for n in range(5, 15)}, **{n: 2 for n in range(15, 31)},
            **{n: 1 for n in range(33, 121, 3)}}
LATE_SHARE = {2: 0.80, 3: 0.88, 4: 0.93, 5: 0.96, 6: 0.98, 7: 0.99}     # of a day's app_remove GA4 shows at that age


def _aid(n):
    return "ca-app-pub-0000000000000000~90000000%02d" % n


# app_id, name, package, (property, stream) or None
APPS = [
    (_aid(1), "Demo Caller – Test App", "com.demo.caller", (P1, "200000001")),
    (_aid(2), "Demo Flashlight", "com.demo.flashlight", (P1, "200000002")),
    (_aid(3), "Demo Notes", "com.demo.notes", (P2, "200000003")),
    (_aid(4), "Demo QR Scanner", "com.demo.qrscanner", (P2, "200000004")),
    (_aid(5), "Demo Weather", "com.demo.weather", (P3, "200000005")),
    (_aid(6), "Demo Launcher", "com.demo.launcher", (P3, "200000006")),
    (_aid(7), "Demo Wallpapers", "com.demo.wallpapers", (P1, "200000007")),
    (_aid(8), "Demo Broken Stream", "com.demo.broken", (P2, "200000008")),
    (_aid(9), "Demo Just Added", "com.demo.justadded", (P3, "200000009")),
    (_aid(10), "Demo No Package", None, None),
    (_aid(11), "Demo No Stream", "com.demo.nostream", None),
    (_aid(12), "Demo Hidden (not selected)", "com.demo.hidden", (P1, "200000012")),
    (_aid(13), "Demo Caller Copy", "com.demo.caller", None),
    (_aid(14), "Demo Late Drop", "com.demo.latedrop", (P3, "200000013")),
    (_aid(15), "Demo Late Told", "com.demo.latetold", (P2, "200000014")),
]
JUST_ADDED, BROKEN, HIDDEN = _aid(9), _aid(8), _aid(12)


def truths():
    E = E_FINAL
    d = lambda n: E - timedelta(days=n)                                  # noqa: E731

    def rollout(old, new, start):                                       # `new` reaches 10% more of the day's
        def versions(day, a1):                                           # active users every day from `start`
            s = 0.0 if day < start else min(0.9, 0.1 * ((day - start).days + 1))
            return {old: int(a1 * (1 - s)), new: int(a1 * s)} if s else {old: a1}
        return versions

    def by_share(f):                                                    # {version: share} → the Truth's users by version
        return lambda day, a1: {v: int(a1 * x) for v, x in f(day).items() if int(a1 * x)}

    def s32(day):                                                        # the Caller's 3.2 share (rollout below)
        return 0.0 if day < date(2026, 9, 10) else min(0.9, 0.1 * ((day - date(2026, 9, 10)).days + 1))
    flash = shares("1.1", [(date(2026, 9, 1), "1.2", 0.3), (date(2026, 9, 19), "1.3", 0.3)])
    t = {
        "200000001": Truth(d(239), E, lambda c: int(5000 * wave(c)), lags=BIG_LAGS, old_per_day=400, noise=0.03,
                           bump=lambda c: ({1: 60} if c >= date(2026, 9, 11)
                                           else {60: 70} if d(199) <= c <= d(187) else None),
                           upd=lambda c: 12000 if c == date(2026, 9, 10) else 800,
                           versions=rollout("3.1", "3.2", date(2026, 9, 10)), seed=1,
                           ret=lambda c, k: DEFAULT_RET(k), old_act=lambda day: 1 - 0.15 * s32(day),
                           tpu=lambda day, v, new: 150.0 if new else 280.0 * (0.78 if v == "3.2" else 1.0)),
        "200000002": Truth(d(74), E, lambda c: int(400 * wave(c)), noise=0.05, old_per_day=20, seed=2, base0=30000,
                           bump=lambda c: {0: -100, 1: 20} if c >= date(2026, 8, 25) else None,
                           ret=lambda c, k: DEFAULT_RET(k) * (1.2 if c >= date(2026, 9, 2) else 1.0),
                           versions=by_share(flash)),
        "200000003": Truth(d(19), E, 150, noise=0.08, seed=3),
        "200000004": Truth(d(199), E, lambda c: int(35 * wave(c, 0.3)), noise=0.2, seed=4),
        "200000005": Truth(d(149), E, lambda c: int(1500 * wave(c)), noise=0.03, seed=5,
                           old_per_day=lambda c: 600 if c >= date(2026, 9, 12) else 150,
                           versions=rollout("4.0", "4.1", date(2026, 7, 15))),
        "200000006": Truth(d(119), E, lambda c: int(800 * wave(c)), noise=0.04, seed=6,
                           old_per_day=lambda c: 960 if c == E else 60,
                           upd=lambda c: 2400 if c == date(2026, 8, 5) else 200),
        "200000007": Truth(d(99), E, lambda c: int(300 * wave(c)), noise=0.05, old_per_day=10, seed=7,
                           versions=by_share(shares("1.0", [(date(2026, 9, 1), "2.0", 0.06, 0.25)]))),
        "200000008": Truth(d(99), E, 100, seed=8),
        "200000009": Truth(d(29), E, 100, seed=9),
        "200000012": Truth(d(29), E, 100, seed=12),
        "200000013": Truth(d(439), E, lambda c: int(2000 * wave(c)), noise=0.03, old_per_day=50, seed=13,
                           ret=lambda c, k: DEFAULT_RET(k), versions=by_share(shares("1.0", [
                               (d(100), "1.9", 1.0), (d(42), "2.0", 1.0), (d(32), "2.1", 1.0)]))),
        "200000014": Truth(d(239), E, lambda c: int(2000 * wave(c)), noise=0.03, old_per_day=50, seed=14,
                           ret=lambda c, k: DEFAULT_RET(k) - (0.025 if k == 1 and c >= d(49) else 0.0),
                           versions=by_share(shares("3.0", [(d(50), "3.1", 1.0)]))),
    }
    gap = date(2026, 9, 14)                                              # a tracking break: no app_remove that day
    z = t["200000007"]
    z.cells = {k: v for k, v in z.cells.items() if k[1] != gap}
    z.old[gap] = 0
    t0 = E - timedelta(days=399)                                         # test installs long before the launch:
    for i in range((z.start - t0).days):                                 # 0–2 a day on a few testers' phones
        c = t0 + timedelta(days=i)
        k = (c.toordinal() * 37) % 11
        z.new[c] = 2 if k == 0 else 1 if k < 4 else 0
        z.old[c], z.upd[c], z.a1[c], z.a28[c] = 0, 0, z.new[c] + 3, 6
        z.vers[c] = {"1.0": z.a1[c]}
        if z.new[c] and i % 3 == 0:
            z.cells[(c, c + timedelta(days=2))] = 1                      # a tester removed it 2 days later
    z.start = t0
    t["200000006"].short_day = {date(2026, 9, 3): 0.6,                  # cells short at ANY range: incomplete
                                date(2026, 8, 20): 0.94}                 # … and a near-complete one: filled (≈)
    caller = t["200000001"]                                              # install-day USERS kept 150 days only
    caller.users_day = lambda day: 1.0 if (caller.asof - day).days <= 150 else 0.04
    t["200000005"].ret_day = lambda age: 1.0 if age <= 60 else 0.3      # Weather: user data kept 60 days (GA4's old
                                                                         # 2-month retention) — older cohorts read short
    for x in t.values():                                                 # Firebase-like late app_remove
        x.late = lambda age: 1.0 if age > 7 else LATE_SHARE.get(age, 0.8)
    return t


IMPRESSIONS = {"200000007": lambda v: 4.0 * (0.68 if v == "2.0" else 1.0)}   # Wallpapers 2.0: a third fewer ads
# Late Drop: ads per user −15% from E−24 (the days after both 7-day after-windows of v2.0 / v2.1)
IMPRESSIONS_DAY = {"200000013": lambda v, day: 4.0 * (0.85 if day >= E_FINAL - timedelta(days=24) else 1.0)}
LONG_REV = ("200000013", "200000014")        # their whole history (the 30 / 60-day noise reads ≥ 6 months back)


def revenue(tr, today):
    """What build_static.admob_revenue hands the uninstall step: every app's AdMob revenue per Pacific day up to
    yesterday — ~4 ad impressions per active user a day at $2 per 1,000 (the Caller Copy's own few dollars join the
    Caller's: one Play package)."""
    till = today - timedelta(days=1)
    apps = {}
    for aid, _, _, route in APPS:
        if not route or route[1] not in tr:
            continue
        t, ipu = tr[route[1]], IMPRESSIONS.get(route[1], lambda v: 4.0)
        ipd = IMPRESSIONS_DAY.get(route[1], lambda v, day: ipu(v))
        days = {}
        for day in sorted(t.a1):
            if day > till or not t.a1[day] or (day < E_FINAL - timedelta(days=150) and route[1] not in LONG_REV):
                continue
            imp = sum(u * ipd(v, day) for v, u in (t.vers.get(day) or {"1.0": t.a1[day]}).items())
            days[day.isoformat()] = [int(imp * 2000), int(imp)]
        apps[aid] = days
    apps[_aid(13)] = {k: [v[0] // 50, v[1] // 50] for k, v in apps[_aid(1)].items()}
    return {"tz": "America/Los_Angeles", "currency": "USD", "till": till.isoformat(), "apps": apps}


def build_fixture(work_dir):
    """Run the seven builds in `work_dir` → {"dashboard_uninstall", "asset", "cohort_files", "sent", "public_log"}."""
    data_dir, out_dir = os.path.join(work_dir, "data"), os.path.join(work_dir, "site")
    os.makedirs(data_dir, exist_ok=True)
    with open(os.path.join(data_dir, "app_store_ids.json"), "w", encoding="utf-8") as f:
        json.dump({"by_id": {aid: pkg for aid, _, pkg, _ in APPS if pkg}}, f)
    tr = truths()
    streams = {p: [("1", "com.stranger.app")] for p in (P1, P2, P3)}   # + a stream that is none of our apps
    for _, _, pkg, route in APPS:
        if route:
            streams[route[0]].append((route[1], pkg))
    admin = AdminFake({TOK1: [P1, P2], TOK2: [P2, P3]}, streams)
    flags = {"broken_tried": False}

    def app(tok, pid, sid):
        if sid == "200000008":
            flags["broken_tried"] = True

            def fail(body):
                raise RuntimeError("HTTP 500: INTERNAL: backend error")
            return UniStub(tr[sid], tok, pid, sid, fail=fail)
        return UniStub(tr[sid], tok, pid, sid)

    s = dict(settings(), ga4_enabled=True, ga4_client_id="demo-cid", ga4_client_secret="demo-sec",
             ga4_refresh_tokens=json.dumps({OWNER1: RT1, OWNER2: RT2}), ga4_refresh_token="",
             ga4_min_hours=20.0, ga4_retry_hours=3.0, ga4_refetch_days=14, ga4_late_days=7, ga4_rebuild_days=28,
             ga4_max_history_days=1300, ga4_run_budget_sec=900, ga4_streams_ttl_hours=168.0, notify_dry_run=True,
             ga4_active=False)                     # the Uninstall tab alone (the Active users tab: build_active_fixture)
    sent = []
    with contextlib.ExitStack() as st:
        st.enter_context(mock.patch.object(ga4.requests, "get", admin.get))
        st.enter_context(mock.patch.object(ga4.requests, "post", admin.post))
        st.enter_context(mock.patch.object(ga4, "_sleep", lambda s: None))
        st.enter_context(mock.patch.object(ga4, "access_token", lambda c, sec, rt: {RT1: TOK1, RT2: TOK2}[rt]))
        st.enter_context(mock.patch.object(ga4, "Ga4App", app))
        log = st.enter_context(contextlib.redirect_stderr(io.StringIO()))
        for i, now in enumerate(RUN_DAYS):
            final = i == len(RUN_DAYS) - 1
            for x in tr.values():                                          # what GA4 has received by this run
                x.asof = (now + timedelta(hours=5, minutes=30)).date()    # (the properties are on IST)
            catalog = [{"app_id": aid, "app_name": name, "account_id": "pub-demo",
                        "selected": aid != HIDDEN and (final or aid != JUST_ADDED)} for aid, name, _, _ in APPS]
            dashboard = {"apps_catalog": catalog, "kpis": {"revenue": 1.0}}
            flags["broken_tried"] = False
            clock = (lambda: 1e6 if flags["broken_tried"] else 0.0) if final else (lambda: 0.0)
            pt_today = (now - timedelta(hours=7)).date()                   # the AdMob report's day (Pacific, PDT)
            run_uninstall(dashboard, data_dir, out_dir, s, now=now, clock=clock, revenue=revenue(tr, pt_today))
            res = build_static.send_alerts(dashboard, s)                  # dry run: formats, never sends
            sent.append({"run": now.strftime("%Y-%m-%dT%H:%MZ"),
                         "telegram": next((r["text"] for r in res if r["channel"] == "telegram"), None),
                         "email": next((r["body"] for r in res if r["channel"] == "email"), None)})
            if not final:                                                  # the final run's alerts stay "new"
                build_static._uninstall_mark_sent(dashboard, data_dir, s, res)
        public_log = log.getvalue().splitlines()
    with gzip.open(os.path.join(out_dir, "uninstall.json.gz"), "rt", encoding="utf-8") as f:
        asset = json.load(f)
    cohort_files = {}
    for name in sorted(os.listdir(out_dir)):
        if name.startswith("uninstall_c_"):
            with gzip.open(os.path.join(out_dir, name), "rt", encoding="utf-8") as f:
                cohort_files[name] = json.load(f)
    return {"dashboard_uninstall": dashboard["uninstall"], "asset": asset, "cohort_files": cohort_files,
            "sent": sent, "public_log": public_log}


def fixture_json(fx):
    body = {"_about": "Synthetic Uninstall-tab data written by the real build code (python -m "
                      "tests.make_uninstall_fixture). dashboard_uninstall = dashboard.json's \"uninstall\" key; "
                      "asset = site/uninstall.json.gz; cohort_files = site/uninstall_c_<key>.json.gz; sent = what "
                      "each of the 7 daily runs would notify (dry run); public_log = the build-log lines. Made-up "
                      "apps only.",
            "dashboard_uninstall": fx["dashboard_uninstall"], "asset": fx["asset"],
            "cohort_files": fx["cohort_files"], "sent": fx["sent"], "public_log": fx["public_log"]}
    return json.dumps(body, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"


# ── the Active users tab's fixture ───────────────────────────────────────────────────────────────
#
# Its own seven daily builds (the same run days, GA4 data till 17–23 Sep 2026) of made-up apps through the real
# run_uninstall + the Active step, send_alerts (dry run) and the marks — the GA4 fetch stubbed and each run's stores
# written as a fetch on that data day would have left them (tests.uninstall_synth.truncate_store): the scenarios need
# inputs the fake GA4 cannot give (usage not fetched yet, a return edge still being searched, mediation revenue …).
#   * Demo Steady          nothing changes (a 📦 update two months ago)
#   * Demo Old Drop        old users −12% from 13 Sep → a drift alert, opened on a later run and SENT (Telegram)
#   * Demo Install Surge   installs ×2 from 3 Sep, old users flat → never an alert about old users
#   * Demo Rocket          70 days old, +40% a week → "Growing fast", no band, no alert
#   * Demo Ad Price        eCPM −15% in the last settled week, ads per user flat → "Ad price lower" + an info row
#   * Demo Ad Gap          12 days without AdMob rows (its account reported nothing) → "No ad data", never $0
#   * Demo Tracking        0 active users on 19 Sep → Check tracking (watch, e-mail)
#   * Demo D1 Drop         new users come back 4 points less the next day (the newest settled week), a 📦 before it
#   * Demo Usage Wait      sessions / time not fetched yet
#   * Demo Edge In / Out   return data from 20 Jul (fits GA4's old 2-month retention) / from 25 Aug (does not)
#   * Demo Searching       return data still being read back (edge not found yet)
#   * Demo Test Installs   200 days of a few test installs before the launch (hidden)
#   * Demo Tiny            ~10 installs a day, GA4's pooled cohorts empty → "unverified"
#   * Demo Rneg            a day with fewer active users than installs → no returning users that day (null)
#   * Demo Mediation       ads per user −8% while other networks took ~13 points more → capped at watch ("mix")
#   * Demo No GA4          not fetched yet
# Eleven of them show the same −10% eCPM week (24–30 Aug): market-wide.

A_FINAL = E_FINAL
A_RUNS = [(RUN_DAYS[i], A_FINAL - timedelta(days=6 - i)) for i in range(7)]
MKT = (date(2026, 8, 24), date(2026, 8, 30))


def _aaid(n):
    # Demo Ad Gap is the only app of its AdMob account: that account's report has no rows in the gap (a day the account
    # did report, without this app's row, would be a real $0 — never "No ad data")
    return ("ca-app-pub-0000000000000001~91000000%02d" if n == 6 else "ca-app-pub-0000000000000000~91000000%02d") % n


def active_apps():
    """[(app_id, name, package, store, revenue)] — every store ends on A_FINAL (each run cuts it to its data day)."""
    S = A_FINAL - timedelta(days=3)
    mkt = lambda d: 0.9 if MKT[0] <= d <= MKT[1] else 1.0              # noqa: E731

    def q(seed, market=True, **kw):
        base = dict(days=130, end=A_FINAL, noise=0.01, hll=0.01, seed=seed, rev_tz="America/Los_Angeles")
        if market and "ecpm" not in kw:
            kw["ecpm"] = lambda d: 2.0 * mkt(d)
        return make_active_store(**dict(base, **kw))
    drop, surge, cut = date(2026, 9, 13), date(2026, 9, 3), S - timedelta(days=12)
    lo = S - timedelta(days=7)
    out = [
        (1, "Demo Steady", q(21, versions=shares("1.0", [(A_FINAL - timedelta(days=60), "1.1", 0.3)]))),
        (2, "Demo Old Drop", q(22, old=lambda d: 20000 * (0.88 if d >= drop else 1.0))),
        (3, "Demo Install Surge", q(23, new=lambda c: 4000 if c >= surge else 2000)),
        (4, "Demo Rocket", q(24, market=False, days=70, new=30,
                             old=lambda d: 1000 * 1.4 ** ((d - (A_FINAL - timedelta(days=69))).days / 7))),
        (5, "Demo Ad Price", q(25, ecpm=lambda d: 2.0 * mkt(d) * (0.85 if d >= S - timedelta(days=6) else 1.0))),
        (6, "Demo Ad Gap", q(26)),
        (7, "Demo Tracking", q(27, a1={S - timedelta(days=1): 0})),
        (8, "Demo D1 Drop", q(28, new=2000, versions=shares("1.0", [(lo - timedelta(days=2), "1.2", 0.3)]),
                              rho=lambda c, k: DEFAULT_RET(k) - (0.04 if k == 1 and lo <= c <= S - timedelta(days=1)
                                                                 else 0.0))),
        (9, "Demo Usage Wait", q(29, usage=False)),
        (10, "Demo Edge In", q(30, days=150, ret_edge=date(2026, 7, 20))),
        (11, "Demo Edge Out", q(31, ret_edge=date(2026, 8, 25))),
        (12, "Demo Searching", q(32, ret_edge="searching", ret_days=60)),
        (13, "Demo Test Installs", q(33, market=False, days=110, pre_days=200)),
        (14, "Demo Tiny", q(34, market=False, new=10, old=300, zero_t=True)),
        (15, "Demo Rneg", q(35, a1={S - timedelta(days=3): 480})),
        (16, "Demo Mediation", q(36, ipu=lambda d, v: 4.0 * (0.92 if d >= cut else 1.0),
                                 other=lambda d: 0.02 if d < cut else 0.15)),
    ]
    apps = []
    for n, name, (st, rv) in out:
        aid, pkg = _aaid(n), "com.demo.act%02d" % n
        st.update(app_id=aid, package=pkg, property_id="3000000%02d" % n, stream_id="4000000%02d" % n)
        if name == "Demo Ad Gap":
            for k in range(39, 51):
                rv["days"].pop((A_FINAL - timedelta(days=k)).isoformat(), None)
        apps.append((aid, name, pkg, st, rv))
    return apps


def build_active_fixture(work_dir):
    """Seven daily builds of the Active users apps → {"dashboard_active", "dashboard_uninstall", "app_files", "portfolio",
    "sent", "public_log"} (the site's per-app files by key; portfolio = its All-apps daily file)."""
    from admob_iq.fetch import ga4_uninstall as gu
    data_dir, out_dir = os.path.join(work_dir, "data"), os.path.join(work_dir, "site")
    os.makedirs(os.path.join(data_dir, "ga4_uninstall"), exist_ok=True)
    apps = active_apps()
    none_id = _aaid(17)
    with open(os.path.join(data_dir, "app_store_ids.json"), "w", encoding="utf-8") as f:
        json.dump({"by_id": dict({aid: pkg for aid, _, pkg, _, _ in apps}, **{none_id: "com.demo.act17"})}, f)
    state = gu._state_default()
    state["routes"].update(fetched_at="2026-09-19T01:00:00Z", by_package={
        pkg: {"property_id": st["property_id"], "stream_id": st["stream_id"], "owner": OWNER1}
        for _, _, pkg, st, _ in apps})
    gu.save_state(data_dir, state)
    s = dict(settings(), ga4_enabled=True, ga4_client_id="demo-cid", ga4_client_secret="demo-sec",
             ga4_refresh_tokens=json.dumps({OWNER1: RT1}), ga4_refresh_token="", ga4_late_days=7,
             notify_dry_run=True, ga4_active=True, ga4_retention_changed="2026-09-26")
    catalog = [{"app_id": aid, "app_name": name, "account_id": "pub-demo", "selected": True}
               for aid, name, _, _, _ in apps] + [{"app_id": none_id, "app_name": "Demo No GA4",
                                                   "account_id": "pub-demo", "selected": True}]
    status = {"counts": {"selected": len(catalog), "with_ga4": len(apps), "fetched": 0, "full": 0, "fresh": len(apps),
                         "failed": 0, "deferred": 0, "no_ga4": 1}, "apps": {}, "no_ga4": {}, "discovery": None}
    sent, log_lines = [], []
    with contextlib.ExitStack() as st_:
        st_.enter_context(mock.patch.object(gu, "refresh_all", lambda *a, **k: json.loads(json.dumps(status))))
        log = st_.enter_context(contextlib.redirect_stderr(io.StringIO()))
        for i, (now, E) in enumerate(A_RUNS):
            final = i == len(A_RUNS) - 1
            till = E + timedelta(days=1)
            rev = {"tz": "America/Los_Angeles", "currency": "USD", "till": till.isoformat(), "apps": {}, "all_apps": {}}
            for aid, _, _, st, rv in apps:
                cut = truncate_store(st, E)
                cut["fetched_at"] = (now - timedelta(hours=10)).strftime("%Y-%m-%dT%H:%M:%SZ")
                gu.save_store(gu.store_path(data_dir, aid), cut)
                rev["apps"][aid] = {k: v for k, v in rv["days"].items() if k <= till.isoformat()}
                if rv.get("all_days"):
                    rev["all_apps"][aid] = {k: v for k, v in rv["all_days"].items() if k <= till.isoformat()}
            dashboard = {"apps_catalog": catalog, "kpis": {"revenue": 1.0}, "alerts": {"items": []}}
            build_static._uninstall_step(dashboard, data_dir, out_dir, s, revenue=rev, now=now)   # pinned clock
            res = build_static.send_alerts(dashboard, s)
            sent.append({"run": now.strftime("%Y-%m-%dT%H:%MZ"),
                         "telegram": next((r["text"] for r in res if r["channel"] == "telegram"), None),
                         "email": next((r["body"] for r in res if r["channel"] == "email"), None)})
            if not final:
                build_static._uninstall_mark_sent(dashboard, data_dir, s, res)
        log_lines = log.getvalue().splitlines()
    files = {}
    for r in dashboard["active"]["apps"]:
        with gzip.open(os.path.join(out_dir, r["file"]), "rt", encoding="utf-8") as f:
            files[r["key"]] = json.load(f)
    port = None
    if dashboard["active"].get("portfolio"):
        with gzip.open(os.path.join(out_dir, dashboard["active"]["portfolio"]["file"]), "rt", encoding="utf-8") as f:
            port = json.load(f)
    return {"dashboard_active": dashboard["active"], "dashboard_uninstall": dashboard["uninstall"], "app_files": files,
            "portfolio": port, "sent": sent, "public_log": log_lines}


def active_fixture_json(fx):
    body = {"_about": "Synthetic Active-users-tab data written by the real build code (python -m "
                      "tests.make_uninstall_fixture). dashboard_active = dashboard.json's \"active\" key; "
                      "dashboard_uninstall = its \"uninstall\" key for the same made-up apps; app_files = "
                      "site/active_<key>.json.gz by key; portfolio = site/active_portfolio.json.gz (the All-apps "
                      "daily series); sent = what each of the 7 daily runs would notify (dry run); "
                      "public_log = the build-log lines. Made-up apps only.",
            "dashboard_active": fx["dashboard_active"], "dashboard_uninstall": fx["dashboard_uninstall"],
            "app_files": fx["app_files"], "portfolio": fx["portfolio"], "sent": fx["sent"],
            "public_log": fx["public_log"]}
    return json.dumps(body, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"


def main():
    from tests.uninstall_synth import legacy_alert_policy
    legacy_alert_policy()                         # (the showcase: every alert kind, the policy off)
    with tempfile.TemporaryDirectory() as tmp:
        text = fixture_json(build_fixture(tmp))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s (%d KB)" % (os.path.relpath(OUT), len(text.encode("utf-8")) // 1024))
    with tempfile.TemporaryDirectory() as tmp:
        text = active_fixture_json(build_active_fixture(tmp))
    with open(OUT_ACTIVE, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s (%d KB)" % (os.path.relpath(OUT_ACTIVE), len(text.encode("utf-8")) // 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
